{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" . }}-mysql
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/component: mysql
    {{- include "petclinic.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "petclinic.fullname" . }}-mysql
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ include "petclinic.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
      {{- include "petclinic.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mysql
        {{- include "petclinic.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: 3306
              name: mysql
          env:
            {{- if .Values.mysql.rootPasswordEmpty }}
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            {{- end }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password | quote }}
          startupProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "--protocol=tcp"]
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "--protocol=tcp"]
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "--protocol=tcp"]
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
{{- end }}
