apiVersion: v1
kind: Secret
metadata:
  name: {{ include "petclinic.fullname" . }}-db
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_URL: {{ .Values.db.url | quote }}
  MYSQL_USER: {{ .Values.db.user | quote }}
  MYSQL_PASS: {{ .Values.db.password | quote }}
